wandb_version: 1

K:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: huggingface
    huggingface_version: 4.9.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      4: 3.6.13
      5: 0.11.2
      6: 4.9.1
      8:
      - 5
activation_function:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: medium
device:
  desc: null
  value: cpu
dropout:
  desc: null
  value: 0.1
embed_dim:
  desc: null
  value: 64
env:
  desc: null
  value: dqn_loc
learning_rate:
  desc: null
  value: 0.0001
log_to_wandb:
  desc: null
  value: true
max_iters:
  desc: null
  value: 100
mode:
  desc: null
  value: normal
model_type:
  desc: null
  value: dt
n_head:
  desc: null
  value: 8
n_layer:
  desc: null
  value: 2
num_eval_episodes:
  desc: null
  value: 100
num_steps_per_iter:
  desc: null
  value: 10
pct_traj:
  desc: null
  value: 1.0
sentence_tensor_length:
  desc: null
  value: 170
warmup_steps:
  desc: null
  value: 5
weight_decay:
  desc: null
  value: 0.0001
